package com.gilbos.standa.util;

public enum UpdateArgs {
    FILES_NEW, FILES_NEW_ERRORS, FILES_ADDED, FILES_ADDED_ERRORS, START_READING_FILES, END_READING_FILES,
    CSV_LINE_ERROR, FILTERS_CHANGED, CHANGED_Y_AXIS_VALUES, CHANGED_SETTINGS, CHANGED_X_AXIS_VALUES, HOVER,
    UNHOVER, UPDATE_VISIBILITY
}
